algoritmo "Enquanto"

var
alturaMarcelo, alturaJoao, crescimentoMarcelo, crescimentoJoao : real
idade: inteiro

inicio

alturaMarcelo <- 1.20
alturaJoao <- 1.05
crescimentoMarcelo <- 0.05
crescimentoJoao <- 0.07
idade <- 8

enquanto alturaMarcelo >= alturaJoao faca
         alturaMarcelo <- alturaMarcelo + cresMOD e DIVcimentoMarcelo
         alturaJoao <- alturaJoao + crescimentoJoao
         idade <- idade + 1
         
fimenquanto

Escreval ("Idade: ", idade)
Escreval ("Altura João: ", alturaJoao)
Escreval ("Altura do Marcelo: ", alturaMarcelo)


fimalgoritmo
