algoritmo "Para"

var
i, aleatorioMinimo, aleatorioMaximo, incremento : inteiro

inicio

repita
aleatorio 1 , 100
          leia (aleatorioMinimo)
          leia (aleatorioMaximo)
aleatorio off
ate aleatorioMaximo >= aleatorioMinimo
limpatela

aleatorio 1,5
leia (incremento)
aleatorio off
limpatela

para i de aleatorioMinimo ate aleatorioMaximo passo incremento faca
     escreval(i)
fimpara

fimalgoritmo
